### ISSUE TITLE
Dermatology Dataset

### ISSUE THREAD

**Issue by rahulv54** [izmailovpavel/spurious_feature_learning#1]
Is there code to replicate the dermatology dataset?

**Comment by izmailovpavel** [comment]
Hey @rahulv54, do you mean the CXR chest X-ray dataset? 

You can find a description of the data here:
![image](https://user-images.githubusercontent.com/14368801/197593088-9498053c-4eb4-43ee-bb01-d73f18e665a0.png)

The spurious labels are not publicly available, we reached out to the authors of _"Hidden stratification causes clinically
meaningful failures in machine learning for medical imaging"_, in particular Lauren Oakden-Rayner (https://laurenoakdenrayner.com/) to get these labels.

**Comment by rahulv54** [comment]
Thank you.

**Comment by rahulv54** [comment]
Oh yes, thank you.
