### ISSUE TITLE
Difference between paper and code

### ISSUE THREAD

**Issue by Jasonlee1995** [izmailovpavel/spurious_feature_learning#4]
<img width="500" alt="image" src="https://github.com/izmailovpavel/spurious_feature_learning/assets/49643709/830e36fc-1c26-4e65-90b2-577bdb5c5e50">

https://github.com/izmailovpavel/spurious_feature_learning/blob/main/data/data_transforms.py#L106-L123

In the Appendix of the paper, test_transform includes RRC which seems weird.

I checked the code and it seems fine for me.

I think that the paper has some typo, but just wanna double-check which is right.

**Comment by pavel-izmailov** [comment]
Hey @Jasonlee1995! You are right, the test transfrom should not include RRC. Thank you for letting me know!
