### ISSUE TITLE
Question about the claim `Group robustness methods perform well because they improve the last linear layer, not the underlying feature representations`

### ISSUE THREAD

**Issue by Jasonlee1995** [izmailovpavel/spurious_feature_learning#5]
Hi.

I really enjoyed reading the paper, but I am confused about one of the claims mentioned in the paper.

<img width="600" alt="image" src="https://github.com/izmailovpavel/spurious_feature_learning/assets/49643709/53842fc9-3a76-46d6-8400-c6485b01945c">
<img width="600" alt="image" src="https://github.com/izmailovpavel/spurious_feature_learning/assets/49643709/949bfe4a-a714-4c8f-bd9e-244ebf13b206">

Claim : `Group robustness methods such as group DRO perform well because they improve the last linear layer, not the underlying feature representations.`

Reason : `if the core feature was better represented by group robustness methods, we would expect to see a significant improvement over ERM after applying DFR.`

`ERM model also learns core features well` is correct, but I don't think the upper claim is right.

To show that the feature representations of 2 models are similar, the experiments of s-DFR must be added on the Figure.

For example, if the group DRO DFR s-WGA and ERM DFR s-WGA is similar, we can analyze that group robustness methods also learns spurious feature and we can maybe conclude that `group robustness methods perform well because they improve the last linear layer, not the underlying feature representations`.

If the group DRO DFR s-WGA and ERM DFR s-WGA is not similar, we can say that group robustness methods do not learn spurious attribute feature, which results that your claim is not right.

Is there any experiment results of DFR s-WGA on `Section 5. ERM vs Group Robustness Training`?

\+ have you also tried using more bigger reweighted dataset? I think the size of the reweighted dataset may change the result.

**Comment by pavel-izmailov** [comment]
Hey @Jasonlee1995! Note that we are not claiming that GroupDRO and ERM are learning identical features, that is indeed not true. You are right that the spurious feature is (I believe) less decodable from Group-DRO than from ERM. However, we are making the claim that the core feature is not better decodable from the Group-DRO features than from ERM features, i.e. a linear probe from them gives similar performance. In other words, GroupDRO does not learn a better representation of the core feature.

We have not explored making the reweighting dataset much larger, as we are limited by the size of the original dataset. If you do test it, would be curious to know the results!
